freelanceExchange/base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index')
]

freelanceExchange/freelanceExchange/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('user/', include('users.urls')),
    path('talent/', include('talents.urls')),
    path('task/', include('tasks.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

freelanceExchange/users/urls.py
from django.urls import path
from . import views
from .views import *

urlpatterns = [

    path('register/', RegisterWizard.as_view(), name='register'),
    path('logout/', views.logout_user, name='logout'),
    path('freelancer_login/', FreelanceLogin.as_view(), name='freelancer_login'),
    path('serves_add/', views.serves_add, name='serves_add'),
    path('profile_update/', views.profile_update, name='profile_update'),
    path('login/', views.login_user, name='login_user'),
    path('profile/<str:pk>/', views.profile, name='profile'),
    path('all_messages/', views.all_messages, name='all_messages'),
    path('chat/<str:pk>/', views.chat, name='chat'),
    path('leave_review/<str:pk>/', views.leave_review, name='leave_review'),
    path('language_add/', views.language_add, name='language_add')
]

freelanceExchange/talents/models.py
from django.db import models
from users.models import Freelancer, Services, Customer

CURRENCY = (
    ('ruble', '₽'),
    ('dollar', '$'),
    ('euro', '€')
)


class Talent(models.Model):
    owner = models.ForeignKey(Freelancer, on_delete=models.CASCADE)
    service = models.ForeignKey(Services, on_delete=models.CASCADE, default=1, verbose_name='Специализация')
    title = models.CharField(max_length=250, verbose_name='Ваш заголовок')
    descriptions = models.TextField(verbose_name='Описание')
    time_created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    time_updated = models.DateTimeField(auto_now=True, verbose_name='Дата обновления')
    skills = models.ManyToManyField('Skills', blank=True, verbose_name='Навыки')
    is_published = models.BooleanField(default=False, verbose_name='Опубликовать')

    def __str__(self):
        return f"{self.title}"

    class Meta:
        ordering = ['-time_updated']


class HourlyRate(models.Model):
    owner = models.ForeignKey(Talent, on_delete=models.CASCADE)
    rate = models.IntegerField(verbose_name='Почасовая ставка')
    currency = models.CharField(choices=CURRENCY, default='ruble', max_length=200, verbose_name='Валюта')

    def __str__(self):
        return f'{self.owner}'


class Skills(models.Model):
    title = models.CharField(max_length=255, verbose_name='Название')

    def __str__(self):
        return self.title

freelanceExchange/tasks/models.py
from django.db import models
from users.models import Customer, Freelancer
from talents.models import Skills

CURRENCY = (
    ('ruble', '₽'),
    ('dollar', '$'),
    ('euro', '€')
)


class Budget(models.Model):
    NAME = (('hourly_rate', 'Почасовая ставка'), ('fix', 'Фиксированная цена'))
    owner = models.ForeignKey('Task', on_delete=models.CASCADE)
    name = models.CharField(max_length=250, choices=NAME)
    min_price = models.IntegerField(null=True, blank=True)
    max_price = models.IntegerField(null=True, blank=True)
    fix_price = models.IntegerField(null=True, blank=True)
    currency = models.CharField(choices=CURRENCY, default='ruble', max_length=200)

    def __str__(self):
        return f'{self.owner.title}'


class Task(models.Model):
    EXPERIENCE = (
        ('junior', 'Начальный уровень'),
        ('middle', 'Средний уровень'),
        ('senior', 'Эксперт')
    )

    AMOUNT_OF_WORK = (
        ('tiny', 'Менее 1 месяца'),
        ('little', 'От 1 до 3 месяцев'),
        ('medium', 'От 3 до 6 месяцев'),
        ('big', 'Более 6 месяцев')
    )

    owner = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='tasks')
    title = models.CharField(max_length=200, verbose_name='Заголовок')
    experiences = models.CharField(max_length=200, choices=EXPERIENCE, verbose_name='Уровень опыта')
    amount_of_work = models.CharField(max_length=200, choices=AMOUNT_OF_WORK, verbose_name='Объем работы')
    contract_work = models.BooleanField(verbose_name='Работа по контракту')
    description = models.TextField(verbose_name='Описание')
    skills = models.ManyToManyField(Skills, blank=True, verbose_name='Навыки')
    time_created = models.DateTimeField(auto_now_add=True, verbose_name='Создано')
    time_updated = models.DateTimeField(auto_now=True, verbose_name='Обновлено')
    is_published = models.BooleanField(default=False, verbose_name='Опубликовать')
    freelancer_saved = models.ManyToManyField(Freelancer, blank=True, related_name='saved_tasks')
    freelancer_responded = models.ManyToManyField(Freelancer, blank=True, related_name='responded_tasks')
    freelancer_refused = models.ManyToManyField(Freelancer, blank=True, related_name='refused_tasks')

    def __str__(self):
        return f'{self.title}'

    class Meta:
        ordering = ['-time_updated']


class Work(models.Model):
    work = models.OneToOneField(Task, on_delete=models.CASCADE)
    worker = models.ForeignKey(Freelancer, on_delete=models.CASCADE, related_name='worker')
    created = models.DateTimeField(auto_now_add=True)
    time_start = models.DateTimeField(blank=True, null=True)
    time_end = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return f'{self.work}'


class StagesOfWork(models.Model):
    owner = models.ForeignKey(Work, on_delete=models.CASCADE)
    stage = models.TextField()
    done = models.BooleanField(default=False)
    update_time = models.DateTimeField(blank=True, null=True)
    max_term = models.DateTimeField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.stage}'

    class Meta:
        ordering = ['max_term']


class Offers(models.Model):
    task = models.OneToOneField(Task, on_delete=models.CASCADE)
    prospective_employee = models.ForeignKey(Freelancer, on_delete=models.CASCADE, related_name='prospective_employee')
    request_date = models.DateTimeField(auto_now_add=True)
    at_work = models.BooleanField(default=False)

    class Meta:
        ordering = ['-request_date']

    def __str__(self):
        return f'{self.task}'

freelanceExchange/users/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.contrib.auth.models import User
from mptt.models import MPTTModel, TreeForeignKey
from phonenumber_field.modelfields import PhoneNumberField
from .utils import LEVEL, LANGUAGE, MONTH


class Role(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return f'{self.name}'


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=200, null=True, blank=True)
    last_name = models.CharField(max_length=200, null=True, blank=True)
    email = models.EmailField(max_length=500, unique=True)
    username = models.CharField(max_length=200, null=True, blank=True)
    photo = models.ImageField(upload_to='users/%Y/%m/%d/', default='default.jpg')
    country = models.CharField(max_length=200, null=True, blank=True)
    city = models.CharField(max_length=200, null=True, blank=True)
    phone_number = PhoneNumberField(unique=True, null=True, blank=True)
    second_number = PhoneNumberField(null=True, blank=True)
    role = models.ForeignKey(Role, on_delete=models.CASCADE, blank=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.username}'


class Services(MPTTModel):
    name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=255, unique=True, verbose_name='URL')
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')

    class MPTTMeta:
        order_insertion_by = ['name']

    def __str__(self):
        return f'{self.name}'


class Education(models.Model):
    LEVEL = (('secondary', 'Среднее'),
             ('special_secondary', 'Среднее специальное'),
             ('unfinished_higher', 'Неоконченное высшее'),
             ('higher', 'Высшее'),
             ('bachelor', 'Бакалавр'),
             ('master', 'Магистр'),
             ('candidate', 'Кандидат наук'),
             ('doctor', 'Доктор наук'),)
    owner = models.ForeignKey("Freelancer", on_delete=models.CASCADE, null=True, blank=True)
    level = models.CharField(choices=LEVEL, max_length=200, null=True, blank=True)
    institution = models.CharField(max_length=500, blank=True, null=True)
    faculty = models.CharField(max_length=500, blank=True, null=True)
    major = models.CharField(max_length=500, blank=True, null=True)
    start_training = models.IntegerField(null=True)
    end_training = models.IntegerField(null=True)

    def __str__(self):
        return f'{self.major}'


class Freelancer(models.Model):
    EXPERIENCE = (
        ('junior', 'Я новичок'),
        ('middle', 'У меня есть некоторый опыт'),
        ('senior', 'Я эксперт')
    )
    owner = models.OneToOneField(Profile, on_delete=models.CASCADE)
    experiences_for_freelance = models.CharField(max_length=200, choices=EXPERIENCE, blank=True, null=True)
    resume = models.FileField(upload_to='freelancers/resumes/%Y/%m/%d/', blank=True)
    bio = models.TextField(null=True, blank=True)
    serves = models.ManyToManyField(Services, blank=True)
    customer_saved = models.ManyToManyField('Customer', blank=True, related_name='saved_talent')
    customer_invited = models.ManyToManyField('Customer', blank=True, related_name='invited_talent')

    def __str__(self):
        return f'{self.owner}'


class Experience(models.Model):
    owner = models.ForeignKey(Freelancer, on_delete=models.CASCADE)
    organization = models.CharField(max_length=250, verbose_name='Организация')
    post = models.CharField(max_length=250)
    duties = models.TextField(null=True, blank=True)
    work_here = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.post}'


class StartWork(models.Model):
    work = models.ForeignKey(Experience, on_delete=models.CASCADE)
    month = models.CharField(max_length=200, choices=MONTH)
    year = models.IntegerField()

    def __str__(self):
        return f'{self.work}'


class EndWork(models.Model):
    work = models.ForeignKey(Experience, on_delete=models.CASCADE)
    month = models.CharField(max_length=200, choices=MONTH)
    year = models.IntegerField()

    def __str__(self):
        return f'{self.work}'


class Language(models.Model):
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE)
    language = models.CharField(max_length=200, choices=LANGUAGE, blank=True, null=True)
    level = models.CharField(max_length=200, choices=LEVEL, blank=True, null=True)

    def __str__(self):
        return self.language


class Customer(models.Model):
    owner = models.OneToOneField(Profile, on_delete=models.CASCADE, related_name='customer')

    def __str__(self):
        return f'{self.owner}'


class Message(models.Model):
    sender = models.ForeignKey(Profile, on_delete=models.SET_NULL, related_name='sender', null=True, blank=True)
    recipient = models.ForeignKey(Profile, on_delete=models.SET_NULL, related_name='recipient', null=True, blank=True)
    subject = models.CharField(max_length=300, null=True, blank=True)
    body = models.TextField()
    task = models.ForeignKey('tasks.Task', on_delete=models.SET_NULL, null=True, blank=True)
    is_read = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.sender}'


class Feedback(models.Model):
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='owner')
    sender = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True,
                               related_name='sender_feedback')
    rating = models.IntegerField(default=0, blank=True, null=True,
                                 validators=[MaxValueValidator(5), MinValueValidator(1)])
    body = models.TextField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.owner}'

    class Meta:
        ordering = ['-created']

freelanceExchange/users/templates/users/add_language.html
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#myModal">Добавить язык
</button>
<div class="modal fade" id="myModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog ">
        <div class="modal-content">

            <form method="POST" class="form" action="{% url 'language_add' %}" autocomplete="off" id="lang-form">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Добавить язык</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal"
                            aria-label="Close"></button>
                </div>
                {% csrf_token %}
                <div class="modal-body">
                    {% for field in form %}
                    <div class="form__field">
                        <label> {{ field.label }}</label>
                        {{ field}}
                    </div>
                    {% endfor %}
                </div>
                <div class="modal-footer">
                    <input type="hidden" name="return_url" value="{{ request.path }}">
                    <button type="submit" class="btn btn-primary">Добавить</button>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
                </div>
            </form>
        </div>
    </div>
</div>

freelanceExchange/users/templates/users/all_messages.html
{% extends 'base/base.html' %}
{% block content %}

<div class="messages">
    <div class="container">
        <div class="messages__box">
            <h3 class="inbox__title">Сообщения(<span>{{ unread_count }}</span>)</h3>
            <ul class="messages__ul">
                {% for message in send_messages %}
                {% if not message.is_read and message.recipient == request.user.profile %}
                <li class="msg msg--unread">
                    {% else %}
                <li class="msg ">
                    {% endif %}
                    {% if message.recipient != request.user.profile %}
                    <a href="{% url 'chat' message.recipient.id %}">
                        <span class="msg__author">{{ message.recipient.first_name }} </span>
                        <span class="msg__date">{{ message.created }}</span></a>
                    {% elif message.sender != request.user.profile %}
                    <a href="{% url 'chat' message.sender.id %}">
                        <span class="msg__author">{{ message.sender.first_name }} </span>
                        <span class="msg__date">{{ message.created }}</span></a>
                    {% endif %}
                </li>

                {% endfor %}{% include 'base/pagination.html' with queryset=send_messages custom_range=custom_range %}
            </ul>

        </div>
    </div>
</div>

{% endblock %}

freelanceExchange/users/templates/users/biography.html
{% extends 'base/base_no_navbar.html' %}

{% block content %}
<div class="register_block">
    <div class="container">
        <div class="register">
            <h3>Теперь напишите биографию, чтобы рассказать о себе</h3>
            <p>Помогите клиентам узнать о вас получше. В какой работе вы лучше всего разбираетесь? Вы всегда можете
                отредактировать позже</p>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ wizard.management_form }}
                {% for field in wizard.form %}
                <div class="form__field">
                    <label> {{ field.label }}</label>
                    {{ field}}
                </div>
                {% endfor %}
                <div class="div_btn">
                    <input type="submit" value="Дальше" class="btn"></div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

freelanceExchange/users/templates/users/chat.html
{% extends 'base/base.html' %}
{% load static %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
{% block content %}

<div class="chat">
    <div class="container chat">
        <div class="chat__box">
            <div class="chat__info">
                <div class="interlocutor__img">
                    <img src="{{ interlocutor.photo.url }}" alt=""></div>
                <h5>
                    <a href="{% url 'profile' interlocutor.id %}">
                        {{ interlocutor.first_name }} {{ interlocutor.last_name }}</a></h5>
            </div>
            <div class="chat__block">
                {% for message in conversation %}
                {% if message.sender == request.user.profile %}
                <div class="msg__recipient">
                    <div class="chat__msg-recipient">
                        <p>{{ message.body }}</p></div>
                </div>
                {% else %}
                <div class="msg__sender">
                    <div class="chat__msg-sender">

                        <p>{{ message.body }}</p></div>
                </div>
                {% endif %}
                {% endfor %}
            </div>
            <div class="new-msg__block">
                <form action="{% url 'chat' id %}" method="post" class="msg-form">
                    {% csrf_token %}
                    <div class="new-msg">
                        <input type="text" placeholder="Введите сообщение" name="msg">
                    </div>

                </form>
            </div>
        </div>

    </div>
</div>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="{% static 'js/send_message.js' %}">

</script>
{% endblock %}

freelanceExchange/users/templates/users/education.html
{% extends 'base/base_no_navbar.html' %}

{% block content %}
<div class="register_block">
    <div class="container">
        <div class="register">
            <h3>Расскажите о своем образовании </h3>
            <form method="post" enctype="multipart/form-data" action="{% url 'freelancer_login' %}">
                {% csrf_token %}
                {{ wizard.management_form }}
                {% for field in wizard.form %}
                <div class="form__field">

                    <label> {{ field.label }}</label>
                    {{ field}}
                </div>
                {% endfor %}

                <div class="div_btn">
                    <button type="submit" value="{{ wizard.steps.next }}" class="btn">Дальше</button>
                    <button type="submit" value="{{ wizard.steps.prev }}" name="wizard_goto_step" class="btn">Предыдущий
                        шаг
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

freelanceExchange/users/templates/users/freelance_login.html
{% extends 'base/base_no_navbar.html' %}
{% load i18n %}

{% block content %}
<div class="register_block">
    <div class="container">
        <div class="register">
            {% if wizard.steps.step1 == 1 %}
            <h3>Ответьте на несколько коротких вопросов. Вы раньше работали фрилансером?</h3>
            {% elif wizard.steps.step1 == 2 %}
            <h3>Если у вас есть резюме, вы можете его загрузить</h3>
            {% elif wizard.steps.step1 == 3 %}
            <h3>На каких языках вы говорите</h3>
            {% elif wizard.steps.step1 == 4 %}
            <h3>Расскажите о своем образовании </h3>
            {% elif wizard.steps.step1 == 5 %}
            <h3>Расскажите о своем опыте работы</h3>
            {% elif wizard.steps.step1 == 6 %}
            <h3>Теперь напишите биографию, чтобы рассказать о себе</h3>
            <p>Помогите клиентам узнать о вас получше. В какой работе вы лучше всего разбираетесь? Вы всегда можете
                отредактировать позже</p>
            {% endif %}
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div>
                    {{ wizard.management_form }}
                    {% if wizard.form.forms %}
                    {{ wizard.form.management_form }}
                    {% for form in wizard.form.forms %}
                    {{ form.as_table }}
                    {% endfor %}
                    {% else %}
                    {% for field in wizard.form %}
                    {% if field.label in 'start_month' %}
                    {% if field.label == 'start_month' %}
                     <div class="start_work">
                         <label>Начало работы</label>
                        {{ field }}
                    </div>
                    {% else %}
                    <div class="start_work">

                        {{ field }}
                    </div>{% endif %}
                    {% elif field.label in 'end_month' %}
                    {% if field.label == 'end_month' %}
                     <div class="end_work">
                         <label>Окончание работы</label>
                        {{ field }}
                    </div>
                    {% else %}
                    <div class="end_work">
                        {{ field }}
                    </div>
                    {% endif %}
                    {%else %}
                    <div class="form__field">

                        <label> {{ field.label }}</label>
                        {{ field}}
                    </div>
                    {% endif %}

                    {% endfor %}
                    {% endif %}
                    {% if wizard.form.errors %}
                    <div class="alert alert-danger">
                        {{ wizard.form.non_field_errors.as_text }}
                    </div>
                    {%endif%}
                </div>
                {% if wizard.steps.prev %}
                <div class="div_btn">
                    <button name="wizard_goto_step" type="submit" value="{{ wizard.steps.prev }}" class="btn">Предыдущий
                        шаг
                    </button>
                    {% endif %}
                    <input type="submit" value="{% translate 'Отправить' %}" class="btn"/></div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

freelanceExchange/users/templates/users/language.html
{% extends 'base/base_no_navbar.html' %}
{% load static %}
{% block content %}
<div class="register_block">
    <div class="container">
        <div class="register">
            <h3>На каких языках вы говорите</h3>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ wizard.management_form }}
                {% for language in request.user.profile.language_set.all %}
                <p>{{ language.get_language_display }} {{ language.get_level_display }}</p>
                {% endfor%}
                <div class="div_btn">
                    <input type="submit" value="Дальше" class="btn">
                </div>
            </form>
            {% include 'users/add_language.html' %}
        </div>
    </div>
</div>
<script src="{% static 'js/language_add.js' %}"></script>
{% endblock %}

freelanceExchange/users/templates/users/profile.html
{% extends 'base/base.html' %}
{% load my_tags %}
{% load static %}
{% block content %}

<div class="profile_block">
    <div class="container">
        <div class="profile">
            <div class="profile_info">
                <div class="profile__pAbout">
                    <div class="profile_photo">
                        <img src="{{ profile.photo.url }}" alt=""/>
                    </div>
                    <div class="profile_about">
                        <h4>{{ profile.first_name }} {{ profile.last_name|default:"" }}</h4>
                        <p>{{ profile.city|default:"" }} {{ profile.country|default:"" }}</p>
                    </div>
                </div>
                {% if profile.username == request.user.username %}
                {% if request.user.profile.freelancer %}
                {% include 'talents/talent_add_modal.html' %}
                {% endif %}
                <div class="profile_settings">
                    <p class="profile_btn"><a href="{% url 'profile_update' %}">Настройки профиля</a></p>
                </div>
                {% else %}
                <div class="profile__all-btns">

                    {% if tasks %}
                    {% include 'talents/talents-btn.html' %}

                    <button onclick="showSend('{{ freelancer.id }}')" class="btn btn-primary">Нанять</button>
                    <div id="send-{{ freelancer.id }}" class="popup">
                        <h5 class="modal-title">Выберите ваше задание, которое вы хотите предложить
                            фрилансеру</h5>
                        <form action="{% url 'send_offer' %}" method="post">
                            {% csrf_token %}
                            {% with hidden_input_name="freelancer_id" %}
                            {% with hidden_input_value=freelancer.id%}
                            {% with radio_button_name="task_id" %}
                            {% with close_popup_function="closeSend" %}
                            {% include 'talents/invite_btn.html' %}
                            {% endwith %}{% endwith %}{% endwith %}{% endwith %}

                        </form>

                    </div>

                    {% endif %}
                    {% include 'users/leave_review.html' %}
                </div>
                {% endif %}
            </div>
            <hr>
            <div class="profile_base">
                <div class="profile_left">
                    <div class="div_talent">
                        {% for service in talents %}
                        {% if service.owner.owner == request.user.profile %}
                        <p class="btn_service"><a href="?s={{ service.id }}">{{ service }} </a></p>
                        {% else %}
                        {% if service.is_published %}
                        <p class="btn_service"><a href="?s={{ service.id }}">{{ service }} </a></p>
                        {% endif %}
                        {% endif %}
                        {% endfor %}
                    </div>
                    {% if freelancer %}
                    <div class="profile__language">
                        <h5>Языки</h5>
                        {% for language in request.user.profile.language_set.all %}
                        <div class="language">
                            <h6>{{ language.get_language_display }}:</h6>
                            <p>{{ language.get_level_display }}</p></div>
                        {% endfor %}
                    </div>
                    {% if freelancer.education_set.all %}
                    <div class="profile__education">
                        <h5>Образование:</h5>
                        {% for education in freelancer.education_set.all %}
                        <div class="language">
                            <h6>{{ education.institution }}:</h6>
                            <p>{{ education.major }}</p></div>
                        {% endfor %}
                    </div>
                    {% endif %}
                    {% if freelancer.resume %}
                    <div class="profile__resume">
                        <h5>Резюме:</h5><a href="{{ freelancer.resume.url }}" target="_blank"><img
                            src="{% static 'icons/document.png' %}" alt=""></a>
                    </div>
                    {% endif %}
                    {% endif %}
                </div>

                <div class="profile_right">
                    <div class="profile_title">
                        {% if talent %}
                        <h4>{{ talent.title }}</h4>
                        <div class="title_hourlyrate">
                            {% if talent.hourlyrate_set.all %}
                            <h4>

                                {{ talent.hourlyrate_set.first.rate|default:"" }}
                                {{ talent.hourlyrate_set.first.get_currency_display|default:"" }}/час</h4>
                            {% elif talent.budget_set.first.max_price and talent.budget_set.first.min_price %}
                            <h4>
                                до {{ talent.budget_set.first.max_price|default:"" }}
                                {{ talent.budget_set.first.get_currency_display|default:"" }}/час
                            </h4>
                            {% else %}
                            <h4>
                                {{ talent.budget_set.first.fix_price|default:"" }}
                                {{ talent.budget_set.first.get_currency_display|default:"" }}/проект
                            </h4>
                            {% endif %}
                            {% if profile.username == request.user.username and request.user.profile.freelancer %}
                            {% with action_url_del='talent_delete' %}
                            {% with new_id=talent.id %}
                            {% with title=talent.title %}
                            {% with action_url_update='talent_update' %}
                            {% include 'talents/change-del_talent.html' %}
                            {% endwith%}{% endwith%}{% endwith%}{% endwith%}
                            {% endif %}
                        </div>
                        {% endif %}

                    </div>
                    <p>{{ talent.description }}</p>
                    <p>{{ talent.descriptions }}</p>
                    <hr>
                    <div class="profile_skills">

                        <h5>Навыки</h5>

                        <div class="skill_list">
                            {% for skill in talent.skills.all %}
                            <p>{{ skill }}</p>
                            {% endfor %}

                        </div>

                    </div>
                    <hr>
                    <div class="profile_feedbacks">
                        {% if feedbacks %}
                        <h5>Отзывы ({{ average_rating }}) </h5>
                        {% for feedback in feedbacks %}
                        <div class="profile__feedback">
                            <div class="feedback__stars">
                                {{ feedback.rating|default_if_none:"0"|rating_stars }} {{ feedback.created }}
                            </div>
                            <p>{{ feedback.body }}</p>
                        </div>
                        <hr>
                        {% endfor %}
                        {% else %}
                        <h6>Отзывов пока нет</h6>
                        {% endif %}
                        {% include 'base/pagination.html' with queryset=feedbacks custom_range=custom_range %}
                    </div>
                </div>


            </div>
        </div>
    </div>
</div>
{% endblock content %}