freelanceExchange/base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index')
]

freelanceExchange/freelanceExchange/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('user/', include('users.urls')),
    path('talent/', include('talents.urls')),
    path('task/', include('tasks.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

freelanceExchange/tasks/urls.py
from django.urls import path
from . import views
from .views import *

urlpatterns = [
    path('task_add/', TaskWizard.as_view(), name='task_add'),
    path('task_budget/<str:pk>/', views.task_budget, name='task_budget'),
    path('find_work/', views.find_work, name='find_work'),
    path('like_task/', views.like_task, name='like_task'),
    path('task/<str:pk>/', views.task, name='task'),
    path('saved_tasks/', views.saved_tasks, name='saved_tasks'),
    path('offers/', views.my_offers, name='offers'),
    path('my_tasks/', views.my_tasks, name='my_tasks'),
    path('delete_task/<str:pk>/', views.delete_task, name='delete_task'),
    path('update_task/<str:pk>/', views.update_task, name='update_task'),
    path('send_offer/', views.send_offer, name='send_offer'),
    path('accept_offer/<str:pk>/', views.accept_offer, name='accept_offer'),
    path('my_staff/', views.my_staff, name='my_staff'),
    path('work/<str:pk>/', views.work, name='work'),
    path('add_stage/', views.add_stage, name='add_stage'),
    path('done_stage/<str:pk>/', views.done_stage, name='done_stage'),
    path('responded/', views.responded_task, name='responded'),
    path('publish_task/<str:pk>/', views.publish_task, name='publish_task')
]

freelanceExchange/tasks/models.py
from django.db import models
from users.models import Customer, Freelancer
from talents.models import Skills

CURRENCY = (
    ('ruble', '₽'),
    ('dollar', '$'),
    ('euro', '€')
)


class Budget(models.Model):
    NAME = (('hourly_rate', 'Почасовая ставка'), ('fix', 'Фиксированная цена'))
    owner = models.ForeignKey('Task', on_delete=models.CASCADE)
    name = models.CharField(max_length=250, choices=NAME)
    min_price = models.IntegerField(null=True, blank=True)
    max_price = models.IntegerField(null=True, blank=True)
    fix_price = models.IntegerField(null=True, blank=True)
    currency = models.CharField(choices=CURRENCY, default='ruble', max_length=200)

    def __str__(self):
        return f'{self.owner.title}'


class Task(models.Model):
    EXPERIENCE = (
        ('junior', 'Начальный уровень'),
        ('middle', 'Средний уровень'),
        ('senior', 'Эксперт')
    )

    AMOUNT_OF_WORK = (
        ('tiny', 'Менее 1 месяца'),
        ('little', 'От 1 до 3 месяцев'),
        ('medium', 'От 3 до 6 месяцев'),
        ('big', 'Более 6 месяцев')
    )

    owner = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='tasks')
    title = models.CharField(max_length=200, verbose_name='Заголовок')
    experiences = models.CharField(max_length=200, choices=EXPERIENCE, verbose_name='Уровень опыта')
    amount_of_work = models.CharField(max_length=200, choices=AMOUNT_OF_WORK, verbose_name='Объем работы')
    contract_work = models.BooleanField(verbose_name='Работа по контракту')
    description = models.TextField(verbose_name='Описание')
    skills = models.ManyToManyField(Skills, blank=True, verbose_name='Навыки')
    time_created = models.DateTimeField(auto_now_add=True, verbose_name='Создано')
    time_updated = models.DateTimeField(auto_now=True, verbose_name='Обновлено')
    is_published = models.BooleanField(default=False, verbose_name='Опубликовать')
    freelancer_saved = models.ManyToManyField(Freelancer, blank=True, related_name='saved_tasks')
    freelancer_responded = models.ManyToManyField(Freelancer, blank=True, related_name='responded_tasks')
    freelancer_refused = models.ManyToManyField(Freelancer, blank=True, related_name='refused_tasks')

    def __str__(self):
        return f'{self.title}'

    class Meta:
        ordering = ['-time_updated']


class Work(models.Model):
    work = models.OneToOneField(Task, on_delete=models.CASCADE)
    worker = models.ForeignKey(Freelancer, on_delete=models.CASCADE, related_name='worker')
    created = models.DateTimeField(auto_now_add=True)
    time_start = models.DateTimeField(blank=True, null=True)
    time_end = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return f'{self.work}'


class StagesOfWork(models.Model):
    owner = models.ForeignKey(Work, on_delete=models.CASCADE)
    stage = models.TextField()
    done = models.BooleanField(default=False)
    update_time = models.DateTimeField(blank=True, null=True)
    max_term = models.DateTimeField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.stage}'

    class Meta:
        ordering = ['max_term']


class Offers(models.Model):
    task = models.OneToOneField(Task, on_delete=models.CASCADE)
    prospective_employee = models.ForeignKey(Freelancer, on_delete=models.CASCADE, related_name='prospective_employee')
    request_date = models.DateTimeField(auto_now_add=True)
    at_work = models.BooleanField(default=False)

    class Meta:
        ordering = ['-request_date']

    def __str__(self):
        return f'{self.task}'

freelanceExchange/tasks/views.py
from django.shortcuts import render, redirect
from .forms import *
from .models import *
from formtools.wizard.views import SessionWizardView
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from users.models import Message
from .utils import search_tasks
import datetime
from base.utils import get_messages, paginate_data

class TaskWizard(LoginRequiredMixin, SessionWizardView):
    template_name = 'tasks/task_add.html'
    done_template = 'users/index.html'
    success_url = reverse_lazy('index')
    form_list = [TaskTitleForm, TaskSkillForm, AmountOfWorkForm, DescriptionForm]

    def done(self, form_list, **kwargs):
        user = self.request.user.profile.customer
        task = Task.objects.create(
            owner=user,
            title=form_list[0].cleaned_data['title'],
            # skills=Skills.objects.get(title=form_list[1].cleaned_data['skills']),
            amount_of_work=form_list[2].cleaned_data['amount'],
            contract_work=form_list[2].cleaned_data['contract_work'],
            experiences=form_list[2].cleaned_data['experience'],
            description=form_list[3].cleaned_data['description']
        )
        task.skills.set(form_list[1].cleaned_data['skills'])
        task.save()
        return redirect('task_budget', pk=task.id)


def publish_task(request, pk):
    task = Task.objects.get(id=pk)
    context = {
        'task': task
    }
    if request.method == 'POST':
        task.is_published = True
        task.save()
        return redirect('my_tasks')
    return render(request, 'tasks/publish_task.html', context)


@login_required(login_url='login')
def task_budget(request, pk):
    task = Task.objects.get(id=pk)
    form = BudgetForm()
    context = {'form': form, 'task': task}
    if request.method == 'POST':
        currency = ''
        if request.POST['select_min_price'] == request.POST['select_max_price']:
            currency = request.POST['select_min_price']
        else:
            messages.error(request, 'Валюта должна быть одинаковой')
            return render(request, 'tasks/task_budget_form.html', context)

        form = BudgetForm(request.POST)
        if form.is_valid():
            budget = form.save(commit=False)
            budget.owner = task
            if budget.name == 'hourly_rate':
                budget.currency = currency
            else:
                budget.currency = request.POST['select_fix_price']
            budget.save()
            return redirect('publish_task', pk=task.id)
        return render(request, 'tasks/task_budget_form.html', context)

    return render(request, 'tasks/task_budget_form.html', context)


def find_work(request):
    tasks, search_query = search_tasks(request)
    tasks, custom_range = paginate_data(request, tasks, 5)
    context = {'tasks': tasks, 'search_query': search_query, 'custom_range': custom_range}
    context.update(get_messages(request.user.profile))
    if request.GET.get('save'):
        profile = request.user.profile
        tasks = Task.objects.filter(freelancer_saved__owner=profile)
        context = {'tasks': tasks}
        return render(request, 'tasks/find_work.html', context)

    return render(request, 'tasks/find_work.html', context)


@login_required(login_url='login')
def like_task(request):
    profile = request.user.profile
    tasks = Task.objects.filter(freelancer_saved__owner=profile)
    context = {'tasks': tasks}
    context.update(get_messages(request.user.profile))
    if request.method == 'POST':
        task_id = request.POST.get('task_id')
        if task_id:
            task = Task.objects.get(id=task_id)
            if request.user.profile.freelancer in task.freelancer_saved.all():
                task.freelancer_saved.remove(request.user.profile.freelancer)
                task.save()
            else:
                task.freelancer_saved.add(request.user.profile.freelancer)
                task.save()
        return render(request, 'tasks/saved_tasks.html', context)

    return render(request, 'tasks/like_task.html', context)


def task(request, pk):
    job = Task.objects.get(id=pk)
    customer = job.owner
    tasks = Task.objects.filter(owner=customer).filter(is_published=True)
    feedbacks = customer.owner.owner.all()
    context = {'task': job, 'customer': customer, 'tasks': tasks, 'feedbacks': feedbacks}
    context.update(get_messages(request.user.profile))
    if request.method == 'POST':
        task_id = request.POST.get('task_id')
        if task_id:
            task = Task.objects.get(id=task_id)
            task.freelancer_responded.add(request.user.profile.freelancer)
            task.save()
            message = Message.objects.create(
                sender=request.user.profile,
                recipient=task.owner.owner,
                subject='response to a vacancy',
                body=f'Добрый день, мне интересна ваша вакансия {task.title}',
            )
            message.save()
        return render(request, 'tasks/task.html', context, )
    return render(request, 'tasks/task.html', context)


def saved_tasks(request):
    profile = request.user.profile
    tasks = Task.objects.filter(freelancer_saved__owner=profile)
    context = {'tasks': tasks}
    context.update(get_messages(request.user.profile))
    return render(request, 'tasks/saved_tasks.html', context)


def my_offers(request):
    user = request.user.profile.freelancer
    offers = Offers.objects.filter(prospective_employee=user)
    context = {'offers': offers}
    context.update(get_messages(request.user.profile))
    return render(request, 'tasks/offers_page.html', context)


def my_tasks(request):
    profile = request.user.profile.customer
    task_in = Task.objects.filter(owner=profile)
    tasks = task_in.exclude(offers__isnull=False)
    context = {'tasks': tasks}
    context.update(get_messages(request.user.profile))
    return render(request, 'tasks/my_tasks.html', context)


def delete_task(request, pk):
    task = Task.objects.get(id=pk)
    if request.method == 'POST':
        task.delete()
        return redirect('my_tasks')


def update_task(request, pk):
    profile = request.user.profile.customer
    task = profile.tasks.get(id=pk)
    budget = task.budget_set.get(owner=task)
    form_task = TaskForm(instance=task)
    form_budget = BudgetForm(instance=budget)
    context = {'task': task, 'form_task': form_task, 'form_budget': form_budget}

    if request.method == 'POST':
        currency = ''
        if request.POST['select_min_price'] == request.POST['select_max_price']:
            currency = request.POST['select_min_price']
        else:
            messages.error(request, 'Валюта должна быть одинаковой')
            return render(request, 'tasks/update_task.html', context)
        form_task = TaskForm(request.POST, instance=task)
        form_budget = BudgetForm(request.POST, instance=budget)

        if form_task.is_valid() and form_budget.is_valid():
            form_task.save()
            budget = form_budget.save(commit=False)
            budget.owner = task
            if budget.name == 'hourly_rate':
                budget.currency = currency
            else:
                budget.currency = request.POST['select_fix_price']
            budget.save()
            return redirect('my_tasks')

    return render(request, 'tasks/update_task.html', context)


def send_offer(request):
    if request.method == 'POST':
        task_id = request.POST.get('task_id')
        freelancer_id = request.POST.get('freelancer_id')
        if task_id and freelancer_id:
            freelancer = Freelancer.objects.get(id=freelancer_id)
            task = Task.objects.get(id=task_id)
            offer = Offers(
                task=task,
                prospective_employee=freelancer
            )
            offer.save()
            return redirect(request.POST.get('return_url'))
        return redirect(request.POST.get('return_url'))
    return redirect(request.POST.get('return_url'))


def accept_offer(request, pk):
    user = request.user.profile.freelancer
    offer = Offers.objects.get(id=pk)
    if request.method == 'POST':
        answer = request.POST.get('accept')
        if answer == 'true':
            task = offer.task
            task.is_published = False
            task.freelancer_responded.remove(user)
            task.save()
            offer.at_work = True
            offer.save()
            work = Work(
                work=offer.task,
                worker=user
            )
            work.save()
            return redirect('offers')
        elif answer == 'false':
            task = offer.task
            task.freelancer_refused.add(user)
            task.save()
            offer.delete()
            return redirect('offers')
    return redirect('offers')


def my_staff(request):
    try:
        user = request.user.profile.customer
        staff = Work.objects.filter(work__owner=user)
        context = {
            'staff': staff
        }
        context.update(get_messages(request.user.profile))
        return render(request, 'tasks/my_staff.html', context)
    except:
        user = request.user.profile.freelancer
        works = Work.objects.filter(worker=user)
        print(works)
        context = {
            'works': works
        }
        context.update(get_messages(request.user.profile))
        return render(request, 'tasks/my_works.html', context)


def work(request, pk):
    work = Work.objects.get(id=pk)
    stages = StagesOfWork.objects.filter(owner=work)
    context = {
        'work': work,
        'stages': stages,
    }
    context.update(get_messages(request.user.profile))
    return render(request, 'tasks/work.html', context)


def add_stage(request):
    if request.method == 'POST':
        new_stage = request.POST.get('stage')
        max_term = request.POST.get('max-term')

freelanceExchange/tasks/templates/tasks/find_work.html
{% extends 'base/base.html' %}
{% load static %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
{% block content %}
<div class="find-work">
    <div class="container">
        <div class="find-work__box">
            <div class="find-work__search">
                <form action="{% url 'find_work' %}" method="get" id="search">
                    <div class="form__search">
                        <input type="search" placeholder="Поиск работы" name="search_query" value="{{search_query}}"/>
                        <input type="submit" value=""/>
                    </div>
                </form>
            </div>

            <div class="find-work__block">
                <h4>Вакансии, которые могут вам понравиться</h4>
                <div class="find-work__filter">
                    <ul>
                        <li><a href="{% url 'find_work' %}">Все вакансии</a></li>
                        <li><a href="?save=True">Сохраненное</a></li>
                    </ul>
                    <hr/>
                </div>
                {% include 'tasks/like_task.html' %}
                {% include 'base/pagination.html' with queryset=tasks custom_range=custom_range %}
            </div>
        </div>

    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="{% static 'js/liked_jquery.js' %}"></script>
<script src="{% static 'js/search_pag.js' %}"></script>
{% endblock %}

freelanceExchange/tasks/templates/tasks/like_task.html
{% if tasks %}
<div class="find-work__results">
    {% for task in tasks %}
    <div class="find-work__tasks">
        <div class="task_title">
            <h5><a href="{% url 'task' task.id %}">{{ task.title }}</a></h5>
            <form action="{% url 'like_task' %}" method="post" class="my-form">
                {% csrf_token %}
                {% if request.user.profile.freelancer in task.freelancer_saved.all %}
                <input type="hidden" name="task_id" value="{{task.id}}">
                <button type="submit" class="like-btn liked"></button>
                {% else %}
                <input type="hidden" name="task_id" value="{{task.id}}">
                <button type="submit" class="like-btn"></button>
                {% endif %}
            </form>
        </div>
        <div class="tasks__info">
            <h6>{{ task.budget_set.first.get_name_display }}</h6>
            {% if task.budget_set.first.name == 'hourly_rate' %}
            <h6>
                : {{ task.budget_set.first.min_price|default:"" }}-{{ task.budget_set.first.max_price|default:"" }}
                {{ task.budget_set.first.get_currency_display|default:"" }}
            </h6>
            {% elif task.budget_set.first.name == 'fix' %}
            <h6>
                Бюджет: {{ task.budget_set.first.get_currency_display|default:"" }} {{ task.budget_set.first.fix_price|default:"" }}
            </h6>
            {% endif %}
            <p> {{ task.get_experiences_display }}</p>
            <p>Время: {{ task.get_amount_of_work_display }}</p>
            <p>Опубликовано: {{ task.time_updated }}</p>
        </div>
        <p class="task__description">{{ task.description }}</p>
        <div class="skill_list">
            {% for skill in task.skills.all %}
            <p>{{ skill }}</p>
            {% endfor %}
        </div>
    </div>
    <hr/>
    {% endfor %}
    {% else %}
    <h3>Следите за интересующими вас вакансиями</h3>
    <h4>Нажимайте на значок сердца в объявлении о вакансии, чтобы сохранить его на потом.</h4>
</div>

{% endif %}

freelanceExchange/tasks/templates/tasks/liked_task.html
{% if tasks %}
<div class="find-work__results">
    {% for task in tasks %}
    <div class="find-work__tasks">
        <div class="task_title">
            <h5><a href="{% url 'task' task.id %}">{{ task.title }}</a></h5>
            <form action="{% url 'liked_task' %}" method="post" class="my-form">
                {% csrf_token %}
                {% if request.user.profile.freelancer in task.freelancer_saved.all %}
                <input type="hidden" name="task_id" value="{{task.id}}">
                <button type="submit" class="like-btn liked"></button>
                {% else %}
                <input type="hidden" name="task_id" value="{{task.id}}">
                <button type="submit" class="like-btn"></button>
                {% endif %}
            </form>
        </div>
        <div class="tasks__info">
            <p>{{ task.budget_set.first.get_name_display }}</p>
            {% if task.budget_set.first.name == 'hourly_rate' %}
            <p>
                : {{ task.budget_set.first.min_price }}-{{ task.budget_set.first.max_price }}{{
                task.budget_set.first.get_currency_display }}
            </p>
            {% elif task.budget_set.first.name == 'fix' %}
            <p>
                Бюджет: {{ task.budget_set.first.get_currency_display }} {{ task.budget_set.first.fix_price}}
            </p>
            {% endif %}
            <p> {{ task.get_experiences_display }}</p>
            <p>Время: {{ task.get_amount_of_work_display }}</p>
            <p>Опубликовано: {{ task.time_updated }}</p>
        </div>
        <h6>{{ task.description }}</h6>
        <div class="skill_list">
            {% for skill in task.skills.all %}
            <p>{{ skill }}</p>
            {% endfor %}
        </div>
    </div>
    <hr/>
    {% endfor %}
    {% else %}
    <h3>Следите за интересующими вас вакансиями</h3>
    <h4>Нажимайте на значок сердца в объявлении о вакансии, чтобы сохранить его на потом.</h4>
</div>{% endif %}

freelanceExchange/tasks/templates/tasks/my_staff.html
{% extends 'base/base.html' %}
{% block content %}
<div class="staff">
    <div class="container">
        <div class="staff_box">
            {% if staff %}
            {% for worker in staff %}
            <div class="worker">
                <div class="worker__title">
                    <h4><a href="{% url 'work' worker.id %}">{{ worker.work }}</a></h4>
                    <p>Исполнитель: {{ worker.worker.owner.first_name }} {{worker.worker.owner.last_name }}</p>
                </div>
                <div class="worker__btns">
                    <p class="btn"><a href="{% url 'chat' worker.worker.owner.id %}">Сообщения</a></p>
                </div>
            </div>
            <hr>
            {% endfor %}
            {% else %}
            <h4>Упс, пока здесь пусто! Начните сотрудничество</h4>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

freelanceExchange/tasks/templates/tasks/my_tasks.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
<div class="my-tasks">
    <div class="container">
        <div class="my-tasks__box">
            <div class="my-tasks__title">
                <h3>Пубикации о вакансиях</h3>
                <p class="btns__my-task"><a href="{% url 'task_add' %}">Опубликовать новую вакансию</a></p></div>
            <div class="my-tasks__block">
                {% if tasks %}
                {% for task in tasks %}
                <div class="task">
                    <div class="task__about">
                        <h5>{{ task.title }}</h5>
                        <p>Создано {{ task.time_created }}</p>
                        {% if task.is_published %}
                        <p>Сохранено {{ task.time_updated }}</p>
                        {% else %}
                        <p>Черновик - Сохранено {{ task.time_updated }}</p>
                        {% endif %}
                    </div>
                    <div class="task_btns">
                        {% if not task.is_published %}
                        <p class="btns__my-task-change"><a href="{% url 'update_task' task.id %}">Изменить черновик</a>
                        </p>
                        {% else %}
                        <p class="btns__my-task-change"><a href="{% url 'update_task' task.id %}">Изменить</a></p>
                        {% endif %}
                        {% with action_url_del='delete_task' %}
                        {% with new_id=task.id %}
                        {% with title=task.title %}
                        {% with action_url_update='update_task' %}
                        {% with action_url_path='my_tasks' %}
                        {% include 'talents/change-del_talent.html' %}
                        {% endwith%}{% endwith%}{% endwith%}{% endwith%}{% endwith%}
                    </div>
                    <div class="modal fade" id="myModal" tabindex="-1" aria-labelledby="exampleModalLabel"
                         aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content modal__my-task">

                                <form method="POST" class="form" action="{% url 'delete_task' task.id %}"
                                      autocomplete="off">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">Вы действительно хотите удалить
                                            {{ task.title }}</h5>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal"
                                                aria-label="Close"></button>
                                    </div>
                                    {% csrf_token %}
                                    <div class="modal__btns">
                                        <button type="submit">Да</button>
                                        <a href="{% url 'my_tasks' %}">Нет</a></div>

                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <hr>
                {% endfor %}
                {% else %}
                <h4>Тут будут располагаться ваши активные вакансии</h4>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

freelanceExchange/tasks/templates/tasks/my_works.html
{% extends 'base/base.html' %}
{% block content %}
<div class="staff">
    <div class="container">
        <div class="staff_box">
            {% if works %}
            {% for work in works %}
            <div class="worker">
                <div class="worker__title">
                    <h4><a href="{% url 'work' work.id %}">{{ work.work }}</a></h4>
                    <p>Заказчик: {{ work.work.owner.owner.first_name }} {{ work.work.owner.owner.last_name }}</p>
                </div>
                <div class="worker__btns">
                    <p class="btn"><a href="{% url 'chat' work.work.owner.owner.id %}">Сообщения</a></p>
                </div>
            </div>
            <hr>
            {% endfor %}
            {% else %}
            <h4>Упс, пока здесь пусто! Начните сотрудничество</h4>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

freelanceExchange/tasks/templates/tasks/saved_tasks.html
{% extends 'base/base.html' %}

{% load static %}
{% block content %}
<div class="save_task">
    <div class="container">
        <div class="save_task__box">
            <h5>Сохраненные вакансии ({{ tasks.count }})</h5>
            <hr>
            {% include 'tasks/like_task.html' %}
        </div>
    </div>
</div>

{% endblock %}

freelanceExchange/tasks/templates/tasks/task.html
{% extends 'base/base.html'%}
{% load static %}
{% load my_tags %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
{% block content %}

<div class="task">
    <div class="container">
        <div class="task__block">

            <h4>Детали работы</h4>
            <div class="task__content">
                <div class="task__info">
                    <h5>{{ task.title }}</h5>
                    <p>Опубликовано {{ task.time_updated }}</p>
                    <hr>
                    <p> {{ task.description }} </p>
                    <hr>
                    <div class="task__details">
                        <div class="task__amount">
                            <img src="{% static 'icons/get-money.png' %}" alt="">
                            <div class="task__amount-text">
                                <p>{{ task.get_amount_of_work_display }}</p>
                                <p>{{ task.budget_set.first.get_name_display }}</p></div>
                        </div>
                        <div class="task__experience">
                            <img src="{% static 'icons/experience.png' %}" alt="">
                            <div class="task__experience-text">
                                <p>{{ task.get_experiences_display }}</p></div>
                        </div>
                    </div>
                    <hr>
                    <h6>Навыки и опыт</h6>
                    <div class="skill_list">
                        {% for skill in task.skills.all %}
                        <p>{{ skill }}</p>
                        {% endfor %}
                    </div>
                </div>
                <div class="task__customer">
                    <div class="task__btns">
                        <form action="{% url 'task' task.id %}" method="post">
                            {% csrf_token %}
                            {% if request.user.profile.freelancer in task.freelancer_responded.all %}

                            <p class="respond-btn responded">Вы откликнулись</p>
                            {% else %}
                            <input type="hidden" name="task_id" value="{{ task.id }}">
                            <button type="submit" class="respond-btn ">Откликнуться</button>
                            {% endif %}
                        </form>
                        <form action="{% url 'like_task' %}" method="post" class="my-form">
                            {% csrf_token %}
                            {% if request.user.profile.freelancer in task.freelancer_saved.all %}
                            <input type="hidden" name="task_id" value="{{task.id}}">
                            <button type="submit" class="liked-btn like">Сохранено</button>
                            {% else %}
                            <input type="hidden" name="task_id" value="{{task.id}}">
                            <button type="submit" class="liked-btn">Сохранить</button>
                            {% endif %}
                        </form>
                    </div>
                    <hr>
                    <div class="customer__info">
                        <h5>О клиенте</h5>
                        <div class="customer__scores">
                            {% if feedbacks %}
                            <h5>Оценка ({{ feedbacks|average_rating}} из {{ feedbacks.count }} отзывов) </h5>
                            {% else %}
                            <p>Здесь будут звезды оценок</p>
                            {% endif %}
                        </div>
                        <hr>
                        <p>{{ customer.owner.country }}, {{ customer.owner.city }} </p>
                    </div>
                </div>
            </div>
            <div class="customer_another_tasks">
                <h4>
                    Другие открытые вакансии этого заказчика ({{ tasks.count }})
                </h4>
                {% for job in tasks %}
                <p><a href="{% url 'task' job.id %}">{{ job.title }}</a> {{ job.budget_set.first.get_name_display }}</p>
                {% endfor %}
            </div>
        </div>

    </div>
</div>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="{% static 'js/liked_jquery.js' %}">

</script>
{% endblock %}